### ISSUE TITLE
Can't compile correctly when compiling YCSB

### ISSUE THREAD

**Issue by ChengyuzeYang** [SpanDB/SpanDB#10]
Hi, when I tested SpanDB and compiled YCSB in Ubuntu18.04, some warnings occured for the command "cmake ..":

CMake Warning (dev) at CMakeLists.txt:17 (ADD_SUBDIRECTORY):
  The source directory

    /home/SpanDB/ycsb/core

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.23)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**And** when compiling YCSB with command "make", I encountered this fatal error:

[ 25%] Building CXX object CMakeFiles/test.dir/src/test.o
cc1plus: fatal error: CMakeFiles/test.dir/src/test.d: No such file or directory
compilation terminated.
CMakeFiles/test.dir/build.make:75: recipe for target 'CMakeFiles/test.dir/src/test.o' failed
make[2]: *** [CMakeFiles/test.dir/src/test.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/test.dir/all' failed
make[1]: *** [CMakeFiles/test.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Could you provide some suggestions to deal with this frustating problem?

**Comment by haydenp-zhou** [comment]
hi, did you fixed this problem?

**Comment by franchyi** [comment]
As a workaround, please use CMake 3.5 for compiling YCSB, as the latest version has an issue. We're working on a fix and appreciate your patience. Thank you for your understanding!
