### ISSUE TITLE
Can i open two db at same PCIE device in a process?

### ISSUE THREAD

**Issue by haydenp-zhou** [SpanDB/SpanDB#14]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

**Comment by cighao** [comment]
RocksDB does not support opening two DBs in one process, and neither does SpanDB. The feature of "Column Families" may be what you want. It is supported in SpanDB. https://github.com/facebook/rocksdb/wiki/Column-Families
